function write_kml(out_path,data,station_name)
%Joshua Soderholm, Sept 2016
%Climate Research Group, University of Queensland
%
%WHAT:
% exports a profile track to GE from a sounding using the wlat,wlon,h and
% temp fields


%% Generate kml

%initalise
kml_str = '';
kml_str = ge_line_style(kml_str,'line_style',html_color(1,[1,1,0]),2);
kml_str = ge_placemark_style(kml_str,'placemark_style');

%create a line segment between markers
line_str = ge_line_string('',1,data.flight,'line_style','absolute',data.h,data.wlat,data.wlon);
line_str = ge_folder('',line_str,'flight track','',1);
%create placemarkers for each obs
mark_str = '';
for j = 1:length(data.h)
    place_id = [data.flight,'-',datestr(data.wdt(j),'HHMM')];
    %create timestep for marker time
    stop_time = addtodate(data.wdt(j),10,'minute');
    mark_str = ge_placemark(mark_str,1,'placemark_style',place_id,data.temp(j),data.wspd(j),data.wdir(j),data.wlat(j),data.wlon(j),data.h(j),data.wdt(j),stop_time);
end
mark_str = ge_folder('',mark_str,'flight markers','',1);
%collate into folder
kml_str = ge_folder(kml_str,[mark_str,line_str],[data.flight,'-',datestr(data.dt_utc(1),'HHMM')],'',1);
%write out
ge_fn = [datestr(data.dt_utc(1),'yyyymmddHHMM'),'_',station_name,'_ge_output'];
ge_kml_out([out_path,'/',ge_fn],ge_fn,kml_str);

display('processing finished')



function kml_out=ge_line_string(kml_in,vis,name,styleUrl,altitudeMode,rel_alt_vec,lat_vec,lon_vec)
%WHAT: Creates a kml string in the line sereies format using a start and
%end point approach.

kml_out=[''];

header=['<Placemark>',10,...
            '<name>',name,'</name>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...
            '<styleUrl>',styleUrl,'</styleUrl>',10,...
            '<LineString>',10,...
                '<altitudeMode>',altitudeMode,'</altitudeMode>',10,...
                '<coordinates>',10];
            
footer=        ['</coordinates>',10,...
            '</LineString>',10,...
        '</Placemark>',10];
    
            
 for i=1:length(lat_vec)-1
     kml_out=[kml_out,header,...
         sprintf('%.6f,%.6f,%.6f', lon_vec(i), lat_vec(i), rel_alt_vec(i)),10,...
         sprintf('%.6f,%.6f,%.6f', lon_vec(i+1), lat_vec(i+1), rel_alt_vec(i+1)),10,...
         footer];
 end
 
 kml_out=[kml_in,kml_out];
 
function kml_str=ge_line_style(kml_str,Style_id,LineColor,LineWidth)
%WHAT: Generates a line style (colour and width) kml string

out = ['<Style id="',Style_id,'">',10,...
         '<LineStyle>',10,...
             '<width>',num2str(LineWidth),'</width>',10,...
             '<color>',LineColor,'</color>',10,...
         '</LineStyle>',10,...
       '</Style>',10];
 
kml_str=[kml_str,out];
 
function str=html_color(trans,map)
%WHAT:
%converts a colormap in the format [0,1] [r,g,b] and trans [0,1] into a hex
%html string
 
%convert to 255 colormap
map=round(255.*map);
trans=round(255*trans);
%restructure into b,g,r format in hex
str=[ dec2hex(trans,2),dec2hex(map(3),2),dec2hex(map(2),2),dec2hex(map(1),2) ];

function ge_kml_out(filename,name,kml_str)
%WHAT: Saves kml string to file


header = ['<?xml version="1.0" encoding="UTF-8"?>',10,...
    '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">',10,...
    '<Document>',10,...
    '<name>',name,'</name>',10];

footer = [10,'</Document>',10,...
    '</kml>',10];


kmlfilename = strcat(filename,'.kml');

fid = fopen( kmlfilename, 'wt');

    fprintf(fid,'%s',header);
    fprintf(fid,'%s',kml_str);
    fprintf(fid,'%s',footer);  
    
fclose(fid);

function kml_folders_str=ge_folder(kml_folders_str,kml_places_str,name,description,visible)
%WHAT: wraps the input kml in a folder with name, description and
%visibility

out=        ['<Folder>',10,...
                    '<name>',name,'</name>',10,...
                    '<visibility>',num2str(visible),'</visibility>',10,... 
                    '<description>',description,'</description>',10,...
                    kml_places_str,...
             '</Folder>',10];
         
kml_folders_str=[kml_folders_str,out];

function kml_str=ge_placemark_style(kml_str,Style_id)
%WHAT: Generates the style kml for the storm stats ballon with the extended
%data template and the icon http link

out=['<Style id="',Style_id,'">',10,...
        '<BalloonStyle>',10,...
            '<text>',10,...
            '<![CDATA[',10,...
                'Altd: $[flt_alt] km',10,...
                'Temp: $[flt_temp] C',10,...
                'WSpd: $[flt_wspd] m/s',10,...
                'WDir: $[flt_wdir] deg',10,...
            ']]>',10,...
            '</text>',10,...
       '</BalloonStyle>',10,...
       '<IconStyle>',10,...
			'<Icon>',10,...
				'<href>https://maps.google.com/mapfiles/ms/icons/blue-dot.png</href>',10,...
			'</Icon>',10,...
		'</IconStyle>',10,...
    '</Style>',10];

kml_str=[kml_str,out];

function kml_str=ge_placemark(kml_str,vis,Style_id,place_id,flt_temp,flt_wspd,flt_wdir,flt_lat,flt_lon,flt_alt,timeSpanStart,timeSpanStop)
%WHAT: generates kml for the storm stats values (3) using extendeddata as inputs
%(template stored in style). anchored at lat lon at a height of 20km
S = 'yyyy-mm-ddTHH:MM:SSZ';
%build timekml if values inputted, otherwise blank
if isempty(timeSpanStart)
    timekml = '';
else
    timekml = ['<TimeSpan><begin>' datestr(timeSpanStart,S) '</begin><end>' datestr(timeSpanStop,S) '</end></TimeSpan>',10];
end 

out=['<Placemark>',10,...
            '<name>',place_id,'</name>',10,...
            '<styleUrl>',Style_id,'</styleUrl>',10,...ident_id
            '<visibility>',num2str(vis),'</visibility>',10,... 
            timekml,...
            '<ExtendedData>',10,...
                '<Data name="flt_alt">',10,...
                    '<value>',num2str(roundn(flt_alt*0.000305,-2)),'</value>',10,...
                '</Data>',10,...
                '<Data name="flt_temp">',10,...
                    '<value>',num2str(flt_temp),'</value>',10,...
                '</Data>',10,...
                '<Data name="flt_wspd">',10,...
                    '<value>',num2str(flt_wspd),'</value>',10,...
                '</Data>',10,...
                '<Data name="flt_wdir">',10,...
                    '<value>',num2str(flt_wdir),'</value>',10,...
                '</Data>',10,...
            '</ExtendedData>',10,...
            '<Point>',10,...
                '<extrude>1</extrude>',10,...
                '<altitudeMode>absolute</altitudeMode>',10,...
                '<coordinates>',num2str(flt_lon),',',num2str(flt_lat),',',num2str(flt_alt),'</coordinates>',10,...
            '</Point>',10,...
    '</Placemark>',10];
    
kml_str=[kml_str,out];
